enum SubscriptionEvents {
  NEW_MESSAGE = "NEW_MESSAGE",
  NEW_CHAT_CREATED = "NEW_CHAT_CREATED",
  CHAT_REQUEST_ACCEPTED = "MESSAGE_REQUEST_ACCEPTED",

  NEW_TRANSACTION_CREATED = "NEW_TRANSACTION_CREATED",
  TRANSACTION_APPROVED = "TRANSACTION_APPROVED",
  TRANSACTION_STATUS_CHANGED = "TRANSACTION_STATUS_CHANGED",

  NEW_NOTIFICATION = "NEW_NOTIFICATION",
}

export default SubscriptionEvents;
